# Generated by Django 5.0.6 on 2024-06-09 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_rename_chat_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
